### ISSUE TITLE
Typo on page 17

### ISSUE THREAD

**Issue by ahl** [PacktPublishing/Asynchronous-Programming-in-Rust#17]
"This part of the cpu is often etched on the same dye" I think you mean "die"

**Comment by cfsamson** [comment]
Hi, and thank you very much for reporting. You're absolutely correct.

I've reported this as an erratum to the publisher (as well as made a note for myself to fix this in a future revision).

Btw, may I just take the opportunity to thank you for making the Oxide and friends podcast (I'm an avid listener).
