### ISSUE TITLE
can not compile

### ISSUE THREAD

**Issue by rongyi** [PacktPublishing/Asynchronous-Programming-in-Rust#27]
https://github.com/PacktPublishing/Asynchronous-Programming-in-Rust/blob/168ad762351ac55c8e013f3bc7499c611ea534dd/ch07/a-coroutine/src/main.rs#L4

should drop Instant

**Comment by cfsamson** [comment]
Hi, and sorry for the slow response. You're right. This was changed due to a reported erratum by someone else than me, and they didn't test that the example worked afterwards. I'm so sorry about that, and thanks for letting me know! I've reverted the change now and confirmed that it works.
