### ISSUE TITLE
Chapter 7 code doesn't work

### ISSUE THREAD

**Issue by Universal-Quantifier** [PacktPublishing/Asynchronous-Programming-in-Rust#6]
The mark in the book is `coroutine` instead of `future`:
https://github.com/PacktPublishing/Asynchronous-Programming-in-Rust/blob/610dddcde1906d2c03614f29dc34556c9f3cacda/ch07/c-async-await/src/main.rs#L15

**Comment by Universal-Quantifier** [comment]
I see, ignore this...

**Comment by cfsamson** [comment]
I’ll double check when I’m at the computer but it seems to me that the keyword somehow got wrong in the repository. I’ll look into it very soon, thanks for reporting.

**Comment by cfsamson** [comment]
So I checked up on this and you're right. It should have been `coroutine` there, but the `original_main.rs` was correct and that's the code that should be "corofied". I patched it now just to avoid future confusion. Again, thanks for reporting!
