### ISSUE TITLE
Correct some Clippy lints

### ISSUE THREAD

**Issue by Tudyx** [PacktPublishing/Asynchronous-Programming-in-Rust#9]
When executing clippy in the root directory with this command

```sh
fd Cargo.toml --exec cargo clippy --manifest-path
```
It finds some clippy lints, if you find it useful maybe we could correct some of them. Of course they are some which are legitimate like when explicitly set an address to `u64` instead of `usize` because we want to support only x86_64.

**Comment by cfsamson** [comment]
As commented in the other issue, I try to avoid project-wide changes that make the code deviate from the book (even though it's an improvement). If the book ever gets a second edition, it seems natural to attend to the clippy lints wherever it makes sense (some of the suggestions are good, but others corrects something that's intentionally written that way).

**Comment by Tudyx** [comment]
That's makes sense, thank you for your answer
